# Generated by Django 5.2.3 on 2025-06-29 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("swapi_url", models.URLField(unique=True)),
                ("release_date", models.DateField()),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Starship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("swapi_url", models.URLField(unique=True)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("swapi_url", models.URLField(unique=True)),
                ("data", models.JSONField()),
                ("films", models.ManyToManyField(related_name="characters", to="api.film")),
                ("starships", models.ManyToManyField(blank=True, related_name="characters", to="api.starship")),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.character"
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.film"
                    ),
                ),
                (
                    "starship",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.starship"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "character"), name="unique_user_character_vote"),
                    models.UniqueConstraint(fields=("user", "film"), name="unique_user_film_vote"),
                    models.UniqueConstraint(fields=("user", "starship"), name="unique_user_starship_vote"),
                ],
            },
        ),
    ]
